### ISSUE TITLE
The type or namespace name 'Transforms' does not exist.

### ISSUE THREAD

**Issue by wearplugins** [LizzyFox-code/BrgContainer#10]
Assets\Scripts\Samples\BatchDataBuffer\BatchDataBufferSample.cs(1,13): error CS0234: The type or namespace name 'Transforms' does not exist in the namespace 'Unity' (are you missing an assembly reference?)

Please remove reference Unity.Transforms in BatchDataBufferSample.cs.

**Comment by LizzyFox-code** [comment]
Oh, sorry, I have fixed it.
