### ISSUE TITLE
Occlusion culling not working

### ISSUE THREAD

**Issue by wearplugins** [LizzyFox-code/BrgContainer#12]
![image](https://github.com/LizzyFox-code/BrgContainer/assets/83076762/10904f08-8964-4482-b706-ff425b5244f2)

I have hexagonal map with ~400k hexagons (1000 tile per container). I create BatchRendererContainers with Bounds 

var bounds = new Bounds(new Vector3(0, 0, 0), new Vector3(100.0f, 100.0f, 100.0f));
_brgContainer = new BatchRendererGroupContainer(bounds);
 
Bat culling not working.

**Comment by LizzyFox-code** [comment]
Hi! Please check culling result in the Frame Debugger.

**Comment by wearplugins** [comment]
![image](https://github.com/LizzyFox-code/BrgContainer/assets/83076762/79611ff5-1fff-450c-8fb1-0d0da53b8fb1)

It seems that the occlusion still works, but in the scene editor are drawn all the tiles. Productivity in the build is much better than in the editor.
