### ISSUE TITLE
Can it be completely shut down if the Lod is not used?

### ISSUE THREAD

**Issue by yuafa** [LizzyFox-code/BrgContainer#14]
I just want to display a large number of instances and support culling system. However, I found that Lod took quite some time, as shown in the following figure, can it be completely turned off?
<img width="930" alt="Snipaste_2024-05-09_11-49-30" src="https://github.com/LizzyFox-code/BrgContainer/assets/11676927/5f4515ae-0de6-421a-9379-cbe69a0276e4">
200000 instances

**Comment by LizzyFox-code** [comment]
Hi! No, but you can make a fork of this repo and turn off lods.
