### ISSUE TITLE
is Good

### ISSUE THREAD

**Issue by 79loli** [LizzyFox-code/BrgContainer#2]
Looking forward to future tutorials

For example, adding, deleting, modifying, and querying a model

**Comment by LizzyFox-code** [comment]
Thanks! I'll definitely add some samples soon :)

**Comment by LizzyFox-code** [comment]
done!

**Comment by 79loli** [comment]
i need unitypackage   It's really impossible to run the Samples scene

**Comment by LizzyFox-code** [comment]
> i need unitypackage It's really impossible to run the Samples scene

What is wrong?

**Comment by 79loli** [comment]
![image](https://github.com/LizzyFox-code/BrgContainer/assets/76603721/67d52760-bad6-4c88-8a7b-9be2b626bbc6)
Unable to see samples, manually copying into the project will result in various errors,  using unity.Transforms  error  and more

**Comment by 79loli** [comment]
Copy smaple~ join Asset file   ,Scene is miss script

**Comment by 79loli** [comment]
I am developing a game that includes a factory assembly line gameplay. I have optimized the coordinates and rotation operations of 8,000,000 goods and 1,000,000 conveyor belts on CPU 7950x to 30ms. I can't wait to test this project. We can have in-depth communication. Can I obtain contact information outside of GitHub? I am from China

**Comment by LizzyFox-code** [comment]
Ah, I got it! You need to open the Package Manager in Unity and install my tool from UPM.

After that you can import the samples in your project:
![2024-04-12_16-34-24](https://github.com/LizzyFox-code/BrgContainer/assets/26055406/177c0eef-5cea-4749-a925-984f571d9577)

**Comment by LizzyFox-code** [comment]
> I am developing a game that includes a factory assembly line gameplay. I have optimized the coordinates and rotation operations of 8,000,000 goods and 1,000,000 conveyor belts on CPU 7950x to 30ms. I can't wait to test this project. We can have in-depth communication. Can I obtain contact information outside of GitHub? I am from China

Oh, sorry, I only can help you here :(

But you can ask any questions, I will try to help you! ^^

**Comment by 79loli** [comment]
![image](https://github.com/LizzyFox-code/BrgContainer/assets/76603721/65ae2863-8d8b-46d7-a7c5-e0a97d7fee29)
no renderer

**Comment by LizzyFox-code** [comment]
Is it in Play Mode?

**Comment by 79loli** [comment]
![image](https://github.com/LizzyFox-code/BrgContainer/assets/76603721/94d99811-815d-424b-8fea-59d3f6c99701)
yes

**Comment by LizzyFox-code** [comment]
What is version of Unity do you use? Can you check the sample in 2023.1+ Unity version?

**Comment by 79loli** [comment]
> What is version of Unity do you use? Can you check the sample in 2023.1+ Unity version?

6000.0.0b11

**Comment by LizzyFox-code** [comment]
> > What is version of Unity do you use? Can you check the sample in 2023.1+ Unity version?
> 
> 6000.0.0b11

Oh, I didn't check this version, sorry :(

**Comment by 79loli** [comment]
Will there be hiz optimization when using custom BRG？

**Comment by LizzyFox-code** [comment]
> Will there be hiz optimization when using custom BRG？

No. May be in the future, but not soon.
