### ISSUE TITLE
CullingBatchInstancesJob depends on Unity.Entities package

### ISSUE THREAD

**Issue by ilyxa-banchichi** [LizzyFox-code/BrgContainer#5]
Структуры AABB нет в пакете Unity.Mathematics, она тянется из Unity.Entities
https://docs.unity3d.com/Packages/com.unity.entities@0.0/api/Unity.Mathematics.AABB.html

**Comment by LizzyFox-code** [comment]
Ой, спасибо

**Comment by LizzyFox-code** [comment]
fixed
